---
stages:
  - publish

pages:
  stage: publish

  rules:
    - if: '$CI_COMMIT_BRANCH == "add-tracking"'

  image: python:3.8-alpine

  script:
    - apk add --no-cache --update tar curl gzip
    - mkdir -p public/assets/
    - 'curl -L --header "DEPLOY-TOKEN: ${TRACKING_PACKAGE_TOKEN}" --output tracking.tar.gz "${CI_API_V4_URL}/projects/${TRACKING_PROJECT_ID}/packages/generic/tracking/${TRACKING_VERSION}/tracking-${TRACKING_VERSION}.tar.gz"'
    - 'curl -L --header "DEPLOY-TOKEN: ${TRACKING_PACKAGE_TOKEN}" --output tracking_demo_videos.tar.gz "${CI_API_V4_URL}/projects/${TRACKING_PROJECT_ID}/packages/generic/tracking_demo_videos/1.0.0/tracking_demo_videos.tar.gz"'
    - 'curl -L --header "DEPLOY-TOKEN: ${TRACKING_PACKAGE_TOKEN}" --output models.tar.gz "${CI_API_V4_URL}/projects/${TRACKING_PROJECT_ID}/packages/generic/tracking_cfnet_models/1.0.0/tracking_cfnet_models.tar.gz"'
    - tar -zxvf models.tar.gz -C public/assets/
    - tar -zxvf tracking.tar.gz tracking.js && mv tracking.js via-3.x.y/src/js/_via_tracking.js
    - tar -zxvf tracking_demo_videos.tar.gz -C public/assets/
    - (cd via-3.x.y/scripts && python3 pack_via.py video_annotator --enable-tracking)
    - (cd via-3.x.y/scripts && python3 pack_demo.py video_annotator --enable-tracking)
    - |
      cat <<-EOF > public/index.html
      <!DOCTYPE html>
      <html lang="en">
      	<head><title>VGG Image Annotator Tracking demo</title><meta charset="UTF-8"></head>
      	<body>
          <h1> VGG Image Annotator tracking demo </h1>
          <p> 
            You can try the pre-loaded demos listed below or try it on your 
            <br> 
            own videos <a href="./via_video_annotator.html">here</a>.
          </p>
          <ul>
            <li> <a href="./demo.html?video=fish.mp4">Fish in an aquarium</a></li>
            <li> <a href="./demo.html?video=mouse.mp4">Mouse going in circles</a></li>
            <li> <a href="./demo.html?video=moon.mp4">Moon transit in front of sun</a></li>
            <li> <a href="./demo.html?video=david.webm">Person with changing illumination, pose, etc.</a></li>
          </ul>
        </body>
      </html>
      EOF
    - cp via-3.x.y/dist/via_video_annotator.html public/via_video_annotator.html
    - cp via-3.x.y/dist/demo/via_video_annotator.html public/demo.html
    - find public/ -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  
  artifacts:
    paths:
      - public

  tags:
    - docker
